### ISSUE TITLE
libjson segfault

### ISSUE THREAD

**Issue by ian-kelling** [transmission-remote-gtk/transmission-remote-gtk#41]
I hit resume with 122 paused items highlighted and it crashed. In syslog, I see this error:

```
kernel: transmission-re[8727]: segfault at 305cdedd88 ip 00007fd5a92157b9 sp 00007fd5933f4af0 error 4 in libjson-glib-1.0.so.0.200.2[7fd5a920c000+27000]
```

This is on debian stretch,
transmission-remote-gtk 1.3.1-2
libjson-glib-1.0-0 1.2.2-1

I restarted it, and the items were resumed.

**Comment by LaserEyess** [comment]
Possibly related, here's a backtrace of a crash. I'm trying to get steps to reproduce but it seems to be happening randomly. 

```
#0  0x00007f8bb39d427c in g_hash_table_lookup () at /usr/lib/libglib-2.0.so.0
#1  0x00007f8bb57cd9b8 in json_object_get_string_member () at /usr/lib/libjson-glib-1.0.so.0
#2  0x000055b8f71ed85c in torrent_get_name (t=<optimized out>) at torrent.c:93
#3  0x000055b8f71d521d in trg_torrent_props_dialog_constructor (type=<optimized out>, n_construct_properties=<optimized out>, construct_params=<optimized out>) at trg-torrent-props-dialog.c:546
        object = 0x55b8f966c770
        propsDialog = 0x55b8f966c770
        window = 0x55b8f966c770
        priv = 0x55b8f966c3f0
        selection = <optimized out>
        rowCount = 1
        prefs = 0x55b8f8ec6430
        width = <optimized out>
        height = <optimized out>
        json = 0x7f8bb3ce8009 <g_type_value_table_peek+489>
        iter = {stamp = -119281520, user_data = 0x55b8f8cdcec0, user_data2 = 0x55b8f8e359b0, user_data3 = 0x55b8f9a05218}
        notebook = <optimized out>
        contentvbox = <optimized out>
#4  0x00007f8bb3cc554e in  () at /usr/lib/libgobject-2.0.so.0
#5  0x00007f8bb3cc7670 in g_object_new_valist () at /usr/lib/libgobject-2.0.so.0
#6  0x00007f8bb3cc79fa in g_object_new () at /usr/lib/libgobject-2.0.so.0
#7  0x000055b8f71d5a9e in trg_torrent_props_dialog_new (window=0x55b8f8f923a0, treeview=0x55b8f8eef310, torrentModel=0x55b8f8fd88e0, client=0x55b8f8ef50e0) at trg-torrent-props-dialog.c:740
#8  0x000055b8f71efe1b in open_props_cb (w=<optimized out>, win=<optimized out>) at trg-main-window.c:444
        dialog = <optimized out>
#9  0x00007f8bb3cbfc5d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#10 0x00007f8bb3cd3b50 in  () at /usr/lib/libgobject-2.0.so.0
#11 0x00007f8bb3cdc806 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#12 0x00007f8bb3cdd240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#13 0x00007f8bb4fae979 in gtk_widget_activate () at /usr/lib/libgtk-3.so.0
#14 0x00007f8bb4e75fbd in gtk_menu_shell_activate_item () at /usr/lib/libgtk-3.so.0
#15 0x00007f8bb4e76259 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007f8bb4e58e78 in  () at /usr/lib/libgtk-3.so.0
#17 0x00007f8bb3cbfea6 in  () at /usr/lib/libgobject-2.0.so.0
#18 0x00007f8bb3cdc4b4 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#19 0x00007f8bb3cdd240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#20 0x00007f8bb4fac2c5 in  () at /usr/lib/libgtk-3.so.0
#21 0x00007f8bb4e55bdb in  () at /usr/lib/libgtk-3.so.0
#22 0x00007f8bb4e57e33 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#23 0x00007f8bb49609f6 in  () at /usr/lib/libgdk-3.so.0
#24 0x00007f8bb4993275 in  () at /usr/lib/libgdk-3.so.0
#25 0x00007f8bb39e5e38 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#26 0x00007f8bb39e6081 in  () at /usr/lib/libglib-2.0.so.0
#27 0x00007f8bb39e610e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#28 0x00007f8bb3fab96e in g_application_run () at /usr/lib/libgio-2.0.so.0
#29 0x000055b8f71cdf3d in trg_gtkapp_init (argv=0x7fffcbcd9898, argc=1, client=<optimized out>) at main.c:63
        gtk_app = 0x55b8f8d45280
        exitCode = <optimized out>
        exitCode = 0
        client = <optimized out>
#30 0x000055b8f71cdf3d in main (argc=<optimized out>, argv=<optimized out>) at main.c:195
        exitCode = 0
        client = <optimized out>
Undefined command: "exit".  Try "help".
```
